export {default as Home} from "./Home/Home"
export {default as LandingPage} from "./LandingPage/LandingPage"
export {default as BlogPage} from "./BlogPage/BlogPage"
export {default as TeamPage} from "./TeamPage/TeamPage"
export {default as EventPage} from "./EventPage/EventPage"
export {default as PageNotFound} from "./PageNotFound/PageNotFound"
export {default as ArchivePage} from "./ArchivePage/ArchivePage"