export { default as ArchivePage } from "./ArchivePage/ArchivePage";
export { default as BlogPage } from "./BlogPage/BlogPage";
export { default as EventPage } from "./EventPage/EventPage";
export { default as Home } from "./Home/Home";
export { default as LandingPage } from "./LandingPage/LandingPage";
export { default as PageNotFound } from "./PageNotFound/PageNotFound";
export { default as TeamPage } from "./TeamPage/TeamPage";
export { default as LeaderBoardPage } from "./LeaderBoardPage/LeaderBoardPage";
export { default as ResourcesPage } from "./Resources/ResourcesPage";
